[project]
name = "get-sound"
version = "0.1.0"
description = ""
authors = [
    {name = "myridia"}
]
license = {text = "GPL3"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtts (>=2.5.4,<3.0.0)",
    "nuitka (>=4.0.7,<5.0.0)",
    "argparse (>=1.4.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

